<?php

namespace AppBundle\Repository;

/**
 * PrometeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrometeoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPaymentsbyDate($date)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Prometeo p WHERE p.date >= :date ORDER BY p.date ASC')
            ->setParameter('date', $date)
            ->getResult();
    }

    public function countPayments()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p.id)  FROM AppBundle:Prometeo p'
            )
            ->getSingleScalarResult();
    }

}
