<?php

namespace AppBundle\Repository;

/**
 * StatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatesRepository extends \Doctrine\ORM\EntityRepository
{
}
